"""empty message

Revision ID: 152a1cca4937
Revises: 9a957d3cbdfe
Create Date: 2020-06-20 19:01:13.157919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152a1cca4937'
down_revision = '9a957d3cbdfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
